language: python
python:
  - "3.5"
  - "3.4"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python TestModule1.py
  - python Test_bot.py < testing.txt
  - python Test_endgame.py
  - python Test_Stock_Main.py < testing_stock_main.txt
  - python Test_User.py < testing_user.txt